<body class="hold-transition sidebar-mini sidebar-collapse">
<div class="wrapper">
<?php $this->load->view('partial/main/navbar') ?><?php $this->load->view('partial/main/sidebar') ?>
<div class="content-wrapper"><section class="content p-3 p-md-4">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
<style>.erp-hero{background:linear-gradient(135deg,#0f172a,#0f766e);border-radius:18px;color:#fff;padding:22px;box-shadow:0 18px 40px rgba(15,23,42,.24)}.erp-panel{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 12px 30px rgba(15,23,42,.08)}.btn-erp{background:linear-gradient(135deg,#0f172a,#0f766e);border:0;color:#fff}table.dataTable thead th{position:sticky;top:0;background:#f8fafc!important}.icon-chip{width:34px;height:34px;border-radius:10px;background:#eef2ff;display:inline-flex;align-items:center;justify-content:center;color:#1d4ed8}</style>
<div class="erp-hero mb-3 d-flex flex-column flex-md-row justify-content-between gap-3 align-items-md-center"><div><h3 class="mb-1 fw-bold">Master Menu</h3><div class="opacity-75">Konfigurasi sidebar dinamis berdasarkan akses level.</div></div><button class="btn btn-light fw-semibold" id="btnAdd"><i class="fas fa-plus me-1"></i> Tambah Menu</button></div>
<div class="erp-panel p-3"><table class="table table-hover align-middle w-100" id="tableMenu"><thead><tr><th>Menu</th><th>Parent</th><th>URL</th><th>Urutan</th><th>Status</th><th>Aksi</th></tr></thead></table></div>
</section></div></div>
<div class="modal fade" id="modalForm" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="formData"><div class="modal-header"><h5 class="modal-title">Form Menu</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="id_menu"><div class="mb-3"><label class="form-label">Parent Menu</label><select class="form-select" name="parent_id" id="parent_id"><option value="0">Root Menu</option><?php foreach($parents as $p): ?><option value="<?= html_escape($p['id_menu']) ?>"><?= html_escape($p['nama_menu']) ?></option><?php endforeach ?></select></div><div class="mb-3"><label class="form-label">Nama Menu</label><input class="form-control" name="nama_menu" id="nama_menu" required></div><div class="mb-3"><label class="form-label">Icon FontAwesome</label><input class="form-control" name="icon" id="icon" placeholder="fas fa-users"></div><div class="mb-3"><label class="form-label">URL</label><input class="form-control" name="url" id="url" placeholder="master/user-management"></div><div class="row g-3"><div class="col-6"><label class="form-label">Urutan</label><input type="number" class="form-control" name="urutan" id="urutan" value="0"></div><div class="col-6"><label class="form-label">Status</label><select class="form-select" name="status" id="status"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-erp">Simpan</button></div></form></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
$(function(){const modal=new bootstrap.Modal(document.getElementById('modalForm'));const table=$('#tableMenu').DataTable({processing:true,serverSide:true,ajax:{url:'<?= base_url('master/menu/list') ?>',type:'POST'},columns:[{data:null,render:r=>`<span class="icon-chip"><i class="${r.icon||'fas fa-circle'}"></i></span> <span class="fw-semibold ms-1">${r.nama_menu}</span>`},{data:'parent_id'},{data:'url'},{data:'urutan'},{data:'status',render:v=>parseInt(v)===1?'<span class="badge bg-success">Aktif</span>':'<span class="badge bg-secondary">Nonaktif</span>'},{data:null,orderable:false,render:r=>`<button class="btn btn-sm btn-outline-primary btn-edit" data-id="${r.id_menu}"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-outline-danger btn-delete" data-id="${r.id_menu}"><i class="fas fa-trash"></i></button>`}]});$('#btnAdd').click(()=>{$('#formData')[0].reset();$('#id_menu').val('');$('#parent_id').val('0');modal.show();});$('#tableMenu').on('click','.btn-edit',function(){$.getJSON('<?= base_url('master/menu/detail/') ?>'+$(this).data('id'),res=>{if(!res.status){toastr.error(res.message);return;}$.each(res.data,(k,v)=>$('#'+k).val(v));modal.show();});});$('#formData').submit(function(e){e.preventDefault();const id=$('#id_menu').val();$.post(id?'<?= base_url('master/menu/update/') ?>'+id:'<?= base_url('master/menu/save') ?>',$(this).serialize(),res=>{res.status?toastr.success(res.message):toastr.error(res.message);if(res.status){modal.hide();table.ajax.reload(null,false);}},'json');});$('#tableMenu').on('click','.btn-delete',function(){const id=$(this).data('id');Swal.fire({title:'Hapus menu?',icon:'warning',showCancelButton:true,confirmButtonText:'Hapus'}).then(r=>{if(r.isConfirmed)$.post('<?= base_url('master/menu/delete/') ?>'+id,res=>{res.status?toastr.success(res.message):toastr.error(res.message);table.ajax.reload(null,false);},'json');});});});
</script></body>
