CREATE TABLE IF NOT EXISTS `stockopname_recyclebin_input` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `source_id` INT(11) NOT NULL COMMENT 'ID record stockopname_opname yang dihapus',
  `original_source_id` INT(11) NULL COMMENT 'Relasi source_id ke master barang',
  `kode_barang` VARCHAR(50) NOT NULL,
  `nama_barang` TEXT NOT NULL,
  `expired_date` DATE NOT NULL,
  `no_lot` VARCHAR(100) NOT NULL,
  `qty` INT(12) NOT NULL DEFAULT 0,
  `qty_box` INT(12) NOT NULL DEFAULT 0,
  `qty_pcs` INT(12) NOT NULL DEFAULT 0,
  `input_by` VARCHAR(100) NOT NULL,
  `input_at` DATETIME NULL,
  `wilayah` INT(2) NOT NULL DEFAULT 0,
  `tim_opname` INT(2) NOT NULL DEFAULT 0,
  `scan_code` VARCHAR(255) NULL,
  `original_created_at` DATETIME NULL,
  `original_updated_at` DATETIME NULL,
  `deleted_by` VARCHAR(100) NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  `delete_reason` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_recycle_source` (`source_id`),
  KEY `idx_recycle_barang` (`kode_barang`),
  KEY `idx_recycle_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stockopname_opname_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `opname_id` INT(11) NULL,
  `kode_barang` VARCHAR(50) NOT NULL,
  `nama_barang` TEXT NULL,
  `expired_date` DATE NULL,
  `no_lot` VARCHAR(100) NULL,
  `action_type` VARCHAR(30) NOT NULL,
  `action` VARCHAR(30) NULL,
  `changed_fields` TEXT NULL,
  `old_data` LONGTEXT NULL,
  `new_data` LONGTEXT NULL,
  `old_value` LONGTEXT NULL,
  `new_value` LONGTEXT NULL,
  `description` TEXT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `before_qty` INT(12) NULL,
  `after_qty` INT(12) NULL,
  `before_qty_box` INT(12) NULL,
  `after_qty_box` INT(12) NULL,
  `before_qty_pcs` INT(12) NULL,
  `after_qty_pcs` INT(12) NULL,
  `changed_by` VARCHAR(100) NULL,
  `changed_at` DATETIME NULL,
  `ip_address` VARCHAR(45) NULL,
  `user_agent` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_stockopname_opname_log_barang` (`kode_barang`),
  KEY `idx_stockopname_opname_log_opname` (`opname_id`),
  KEY `idx_stockopname_opname_log_action` (`action_type`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Jalankan blok ALTER berikut hanya untuk instalasi yang sudah memiliki tabel log versi lama.
ALTER TABLE `stockopname_opname_log`
  ADD COLUMN IF NOT EXISTS `nama_barang` TEXT NULL AFTER `kode_barang`,
  ADD COLUMN IF NOT EXISTS `expired_date` DATE NULL AFTER `nama_barang`,
  ADD COLUMN IF NOT EXISTS `no_lot` VARCHAR(100) NULL AFTER `expired_date`,
  ADD COLUMN IF NOT EXISTS `action_type` VARCHAR(30) NOT NULL DEFAULT 'EDIT_QTY' AFTER `no_lot`,
  ADD COLUMN IF NOT EXISTS `old_value` LONGTEXT NULL AFTER `new_data`,
  ADD COLUMN IF NOT EXISTS `new_value` LONGTEXT NULL AFTER `old_value`,
  ADD COLUMN IF NOT EXISTS `description` TEXT NULL AFTER `new_value`,
  ADD COLUMN IF NOT EXISTS `created_by` VARCHAR(100) NOT NULL DEFAULT 'system' AFTER `description`,
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME NULL AFTER `created_by`,
  ADD COLUMN IF NOT EXISTS `before_qty` INT(12) NULL AFTER `created_at`,
  ADD COLUMN IF NOT EXISTS `after_qty` INT(12) NULL AFTER `before_qty`,
  ADD COLUMN IF NOT EXISTS `before_qty_box` INT(12) NULL AFTER `after_qty`,
  ADD COLUMN IF NOT EXISTS `after_qty_box` INT(12) NULL AFTER `before_qty_box`,
  ADD COLUMN IF NOT EXISTS `before_qty_pcs` INT(12) NULL AFTER `after_qty_box`,
  ADD COLUMN IF NOT EXISTS `after_qty_pcs` INT(12) NULL AFTER `before_qty_pcs`;

ALTER TABLE `stockopname_manual_input`
  MODIFY `input_source` VARCHAR(30) NOT NULL DEFAULT 'manual_input';
