CREATE TABLE IF NOT EXISTS `stockopname_master_manual_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `source_id` INT(11) NOT NULL,
  `kode_barang` VARCHAR(50) NOT NULL,
  `nama_barang` TEXT NOT NULL,
  `expired_date` DATE NOT NULL,
  `no_lot` VARCHAR(100) NOT NULL,
  `dimensi` INT(12) NOT NULL DEFAULT 0,
  `status` ENUM('PENDING','APPROVED','REJECTED','ADDED') NOT NULL DEFAULT 'PENDING',
  `requested_by` VARCHAR(100) NOT NULL,
  `requested_at` DATETIME NOT NULL,
  `reviewed_by` VARCHAR(100) NULL DEFAULT NULL,
  `reviewed_at` DATETIME NULL DEFAULT NULL,
  `review_note` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_manual_master_source` (`source_id`),
  KEY `idx_manual_master_barang` (`kode_barang`),
  KEY `idx_manual_master_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stockopname_opname_manual` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manual_master_id` INT(11) NOT NULL,
  `source_id` INT(11) NOT NULL,
  `kode_barang` VARCHAR(50) NOT NULL,
  `nama_barang` TEXT NOT NULL,
  `expired_date` DATE NOT NULL,
  `no_lot` VARCHAR(100) NOT NULL,
  `qty` INT(12) NOT NULL DEFAULT 0,
  `qty_pcs` INT(12) NOT NULL DEFAULT 0,
  `qty_box` INT(12) NOT NULL DEFAULT 0,
  `input_by` VARCHAR(100) NOT NULL,
  `input_at` DATETIME NOT NULL,
  `wilayah` INT(2) NOT NULL DEFAULT 0,
  `tim_opname` INT(2) NOT NULL DEFAULT 0,
  `input_source` VARCHAR(30) NOT NULL DEFAULT 'manual',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_manual_opname_master` (`manual_master_id`),
  KEY `idx_manual_opname_source` (`source_id`),
  KEY `idx_manual_opname_barang` (`kode_barang`),
  KEY `idx_manual_opname_source_type` (`input_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
