CREATE TABLE IF NOT EXISTS `tb_pre_po_invoice_adjustment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `no_po` varchar(255) DEFAULT NULL,
  `kd_po` varchar(255) NOT NULL,
  `tgl_transaksi` varchar(25) DEFAULT NULL,
  `kd_suplier` varchar(35) DEFAULT NULL,
  `kd_barang` varchar(35) NOT NULL,
  `satuan` varchar(50) DEFAULT NULL,
  `qty` double NOT NULL DEFAULT 0,
  `harga_satuan` double NOT NULL DEFAULT 0,
  `harga` double NOT NULL DEFAULT 0,
  `harga_diskon` double NOT NULL DEFAULT 0,
  `total_harga` double NOT NULL DEFAULT 0,
  `total_harga_diskon` double NOT NULL DEFAULT 0,
  `tax_percent` double NOT NULL DEFAULT 0,
  `tax` double NOT NULL DEFAULT 0,
  `tax_diskon` double NOT NULL DEFAULT 0,
  `grand_total` double NOT NULL DEFAULT 0,
  `grand_total_diskon` double NOT NULL DEFAULT 0,
  `source_payload` text DEFAULT NULL,
  `synced_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_kd_po_barang` (`kd_po`, `kd_barang`),
  KEY `idx_kd_po` (`kd_po`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
