<body class="hold-transition sidebar-mini sidebar-collapse">
<div class="wrapper">
    <?php $this->load->view('partial/main/navbar') ?>
    <?php $this->load->view('partial/main/sidebar') ?>
    <div class="content-wrapper"><section class="content p-3 p-md-4">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
        <style>.erp-hero{background:linear-gradient(135deg,#1d4ed8,#0891b2);border-radius:18px;color:#fff;padding:22px;box-shadow:0 18px 40px rgba(29,78,216,.22)}.erp-panel{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 12px 30px rgba(15,23,42,.08)}.btn-erp{background:linear-gradient(135deg,#1d4ed8,#0891b2);border:0;color:#fff}table.dataTable thead th{position:sticky;top:0;background:#f8fafc!important}</style>
        <div class="erp-hero mb-3 d-flex flex-column flex-md-row justify-content-between gap-3 align-items-md-center"><div><h3 class="mb-1 fw-bold">Master Jobdesk</h3><div class="opacity-75">Kelola posisi kerja dan kompatibilitas jobdesk legacy.</div></div><button class="btn btn-light fw-semibold" id="btnAdd"><i class="fas fa-plus me-1"></i> Tambah</button></div>
        <div class="erp-panel p-3"><table class="table table-hover align-middle w-100" id="tableJobdesk"><thead><tr><th>Jobdesk</th><th>Deskripsi</th><th>Status</th><th>Aksi</th></tr></thead></table></div>
    </section></div>
</div>
<div class="modal fade" id="modalForm" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="formData"><div class="modal-header"><h5 class="modal-title">Form Jobdesk</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="id_jobdesk"><div class="mb-3"><label class="form-label">Nama Jobdesk</label><input class="form-control" name="nama_jobdesk" id="nama_jobdesk" required></div><div class="mb-3"><label class="form-label">Deskripsi</label><textarea class="form-control" name="deskripsi" id="deskripsi"></textarea></div><div><label class="form-label">Status</label><select class="form-select" name="status" id="status"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-erp">Simpan</button></div></form></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
$(function(){const modal=new bootstrap.Modal(document.getElementById('modalForm'));const table=$('#tableJobdesk').DataTable({processing:true,serverSide:true,ajax:{url:'<?= base_url('master/jobdesk/list') ?>',type:'POST'},columns:[{data:'nama_jobdesk'},{data:'deskripsi'},{data:'status',render:v=>parseInt(v)===1?'<span class="badge bg-success">Aktif</span>':'<span class="badge bg-secondary">Nonaktif</span>'},{data:null,orderable:false,render:r=>`<button class="btn btn-sm btn-outline-primary btn-edit" data-id="${r.id_jobdesk}"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-outline-danger btn-delete" data-id="${r.id_jobdesk}"><i class="fas fa-trash"></i></button>`}]});$('#btnAdd').click(()=>{$('#formData')[0].reset();$('#id_jobdesk').val('');modal.show();});$('#tableJobdesk').on('click','.btn-edit',function(){$.getJSON('<?= base_url('master/jobdesk/detail/') ?>'+$(this).data('id'),res=>{if(!res.status){toastr.error(res.message);return;}$('#id_jobdesk').val(res.data.id_jobdesk);$('#nama_jobdesk').val(res.data.nama_jobdesk);$('#deskripsi').val(res.data.deskripsi);$('#status').val(res.data.status);modal.show();});});$('#formData').submit(function(e){e.preventDefault();const id=$('#id_jobdesk').val();$.post(id?'<?= base_url('master/jobdesk/update/') ?>'+id:'<?= base_url('master/jobdesk/save') ?>',$(this).serialize(),res=>{res.status?toastr.success(res.message):toastr.error(res.message);if(res.status){modal.hide();table.ajax.reload(null,false);}},'json');});$('#tableJobdesk').on('click','.btn-delete',function(){const id=$(this).data('id');Swal.fire({title:'Hapus jobdesk?',icon:'warning',showCancelButton:true,confirmButtonText:'Hapus'}).then(r=>{if(r.isConfirmed)$.post('<?= base_url('master/jobdesk/delete/') ?>'+id,res=>{res.status?toastr.success(res.message):toastr.error(res.message);table.ajax.reload(null,false);},'json');});});});
</script>
</body>
