<body class="hold-transition sidebar-mini sidebar-collapse">
<div class="wrapper">
<?php $this->load->view('partial/main/navbar') ?><?php $this->load->view('partial/main/sidebar') ?>
<div class="content-wrapper"><section class="content p-3 p-md-4">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
<style>.erp-hero{background:linear-gradient(135deg,#4338ca,#0f766e);border-radius:18px;color:#fff;padding:22px;box-shadow:0 18px 40px rgba(67,56,202,.22)}.erp-panel{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 12px 30px rgba(15,23,42,.08)}.btn-erp{background:linear-gradient(135deg,#4338ca,#0f766e);border:0;color:#fff}.perm-table th{position:sticky;top:0;background:#f8fafc;z-index:2}.perm-toggle{width:1.15rem;height:1.15rem}@media(max-width:768px){.matrix-wrap{overflow:auto}}</style>
<div class="erp-hero mb-3 d-flex flex-column flex-md-row justify-content-between gap-3 align-items-md-center"><div><h3 class="mb-1 fw-bold">Akses Level</h3><div class="opacity-75">Role permission matrix: view, add, edit, delete, approve, print.</div></div><button class="btn btn-light fw-semibold" id="btnAdd"><i class="fas fa-plus me-1"></i> Tambah Akses</button></div>
<div class="row g-3"><div class="col-lg-5"><div class="erp-panel p-3"><table class="table table-hover align-middle w-100" id="tableAkses"><thead><tr><th>Akses</th><th>Status</th><th>Aksi</th></tr></thead></table></div></div><div class="col-lg-7"><div class="erp-panel"><div class="p-3 border-bottom d-flex justify-content-between align-items-center"><div><strong>Permission Matrix</strong><div class="small text-muted" id="matrixTitle">Pilih akses level</div></div></div><div class="p-3 matrix-wrap"><table class="table table-sm perm-table align-middle"><thead><tr><th>Menu</th><th>View</th><th>Add</th><th>Edit</th><th>Delete</th><th>Approve</th><th>Print</th></tr></thead><tbody id="matrixBody"><tr><td colspan="7" class="text-center text-muted py-4">Belum ada akses dipilih.</td></tr></tbody></table></div></div></div></div>
</section></div></div>
<div class="modal fade" id="modalForm" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="formData"><div class="modal-header"><h5 class="modal-title">Form Akses Level</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="id_akses_level"><div class="mb-3"><label class="form-label">Nama Akses</label><input class="form-control" name="nama_akses_level" id="nama_akses_level" required></div><div class="mb-3"><label class="form-label">Deskripsi</label><textarea class="form-control" name="deskripsi" id="deskripsi"></textarea></div><div><label class="form-label">Status</label><select class="form-select" name="status" id="status"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-erp">Simpan</button></div></form></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
$(function(){let activeId=null;const modal=new bootstrap.Modal(document.getElementById('modalForm'));const table=$('#tableAkses').DataTable({processing:true,serverSide:true,ajax:{url:'<?= base_url('master/akses-level/list') ?>',type:'POST'},columns:[{data:'nama_akses_level'},{data:'status',render:v=>parseInt(v)===1?'<span class="badge bg-success">Aktif</span>':'<span class="badge bg-secondary">Nonaktif</span>'},{data:null,orderable:false,render:r=>`<button class="btn btn-sm btn-outline-success btn-matrix" data-name="${r.nama_akses_level}" data-id="${r.id_akses_level}"><i class="fas fa-shield-alt"></i></button> <button class="btn btn-sm btn-outline-primary btn-edit" data-id="${r.id_akses_level}"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-outline-danger btn-delete" data-id="${r.id_akses_level}"><i class="fas fa-trash"></i></button>`}]});
function loadMatrix(id,name){activeId=id;$('#matrixTitle').text(name);$('#matrixBody').html('<tr><td colspan="7" class="text-center py-4">Memuat...</td></tr>');$.getJSON('<?= base_url('master/akses-level/matrix/') ?>'+id,res=>{if(!res.status){toastr.error(res.message);return;}let html='';(res.data||[]).forEach(m=>{html+=`<tr><td><i class="${m.icon||'fas fa-circle'} me-1"></i>${m.nama_menu}</td>${['can_view','can_add','can_edit','can_delete','can_approve','can_print'].map(p=>`<td class="text-center"><input type="checkbox" class="form-check-input perm-toggle" data-menu="${m.id_menu}" data-perm="${p}" ${parseInt(m[p])===1?'checked':''}></td>`).join('')}</tr>`});$('#matrixBody').html(html||'<tr><td colspan="7" class="text-center text-muted py-4">Menu belum tersedia.</td></tr>');});}
$('#matrixBody').on('change','.perm-toggle',function(){$.post('<?= base_url('master/akses-level/update-permission') ?>',{akses_lv_id:activeId,id_menu:$(this).data('menu'),permission:$(this).data('perm'),value:this.checked?1:0},res=>{res.status?toastr.success(res.message):toastr.error(res.message);},'json');});
$('#btnAdd').click(()=>{$('#formData')[0].reset();$('#id_akses_level').val('');modal.show();});$('#tableAkses').on('click','.btn-matrix',function(){loadMatrix($(this).data('id'),$(this).data('name'));});$('#tableAkses').on('click','.btn-edit',function(){$.getJSON('<?= base_url('master/akses-level/detail/') ?>'+$(this).data('id'),res=>{if(!res.status){toastr.error(res.message);return;}$('#id_akses_level').val(res.data.id_akses_level);$('#nama_akses_level').val(res.data.nama_akses_level);$('#deskripsi').val(res.data.deskripsi);$('#status').val(res.data.status);modal.show();});});$('#formData').submit(function(e){e.preventDefault();const id=$('#id_akses_level').val();$.post(id?'<?= base_url('master/akses-level/update/') ?>'+id:'<?= base_url('master/akses-level/save') ?>',$(this).serialize(),res=>{res.status?toastr.success(res.message):toastr.error(res.message);if(res.status){modal.hide();table.ajax.reload(null,false);}},'json');});$('#tableAkses').on('click','.btn-delete',function(){const id=$(this).data('id');Swal.fire({title:'Hapus akses level?',icon:'warning',showCancelButton:true,confirmButtonText:'Hapus'}).then(r=>{if(r.isConfirmed)$.post('<?= base_url('master/akses-level/delete/') ?>'+id,res=>{res.status?toastr.success(res.message):toastr.error(res.message);table.ajax.reload(null,false);},'json');});});});
</script></body>
