CREATE TABLE IF NOT EXISTS `tb_lpb_price_adjustment` (
  `id_adjustment` INT(11) NOT NULL AUTO_INCREMENT,
  `no_adjustment` VARCHAR(50) NOT NULL,
  `id_lpb_salah` INT(11) NOT NULL,
  `id_lpb_adjustment` INT(11) DEFAULT NULL,
  `id_retur_pembelian` INT(11) DEFAULT NULL,
  `nomor_lpb_salah` VARCHAR(50) DEFAULT NULL,
  `nomor_lpb_adjustment` VARCHAR(50) DEFAULT NULL,
  `tanggal_adjustment` DATE NOT NULL,
  `kd_po` VARCHAR(100) DEFAULT NULL,
  `no_po` VARCHAR(100) DEFAULT NULL,
  `kd_supplier` VARCHAR(100) DEFAULT NULL,
  `gudang_id` VARCHAR(30) DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  `alasan_adjustment` TEXT DEFAULT NULL,
  `total_qty` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `total_lpb_salah` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `total_lpb_benar` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `selisih_dpp` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `selisih_ppn` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `selisih_total` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `id_jurnal_lpb_adjustment` INT(11) DEFAULT NULL,
  `id_jurnal_prpp` INT(11) DEFAULT NULL,
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `posted_by` VARCHAR(100) DEFAULT NULL,
  `posted_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id_adjustment`),
  UNIQUE KEY `uk_no_adjustment` (`no_adjustment`),
  KEY `idx_lpb_salah` (`id_lpb_salah`),
  KEY `idx_lpb_adjustment` (`id_lpb_adjustment`),
  KEY `idx_retur` (`id_retur_pembelian`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tb_lpb_price_adjustment_detail` (
  `id_adjustment_detail` INT(11) NOT NULL AUTO_INCREMENT,
  `id_adjustment` INT(11) NOT NULL,
  `id_detail_lpb_salah` INT(11) NOT NULL,
  `id_detail_lpb_adjustment` INT(11) DEFAULT NULL,
  `kd_barang` VARCHAR(100) NOT NULL,
  `nama_barang` VARCHAR(255) DEFAULT NULL,
  `qty` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `no_lot_adjustment` VARCHAR(50) DEFAULT NULL,
  `expired_date_adjustment` DATE DEFAULT NULL,
  `harga_salah` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `harga_benar` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `dpp_salah` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `dpp_benar` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `ppn_salah` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `ppn_benar` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `total_salah` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `total_benar` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `kelompok_dagang` VARCHAR(10) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_adjustment_detail`),
  KEY `idx_adjustment` (`id_adjustment`),
  KEY `idx_detail_salah` (`id_detail_lpb_salah`),
  KEY `idx_detail_adjustment` (`id_detail_lpb_adjustment`),
  KEY `idx_barang_batch` (`kd_barang`, `no_lot_adjustment`, `expired_date_adjustment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
