CREATE TABLE IF NOT EXISTS `tb_retur_pembelian` (
  `id_retur_pembelian` INT(11) NOT NULL AUTO_INCREMENT,
  `no_retur_pembelian` VARCHAR(50) NOT NULL,
  `id_lpb` INT(11) NOT NULL,
  `kd_po` VARCHAR(100) DEFAULT NULL,
  `no_po` VARCHAR(100) DEFAULT NULL,
  `kd_supplier` VARCHAR(100) DEFAULT NULL,
  `tanggal_retur` DATE NOT NULL,
  `gudang_id` VARCHAR(30) DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  `jenis_penyelesaian` VARCHAR(40) NOT NULL DEFAULT 'POTONG_HUTANG',
  `alasan_retur` TEXT DEFAULT NULL,
  `catatan_purchasing` TEXT DEFAULT NULL,
  `catatan_accounting` TEXT DEFAULT NULL,
  `total_dpp` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `total_ppn` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `grand_total` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `id_jurnal` INT(11) DEFAULT NULL,
  `id_jurnal_reversal` INT(11) DEFAULT NULL,
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `submitted_by` VARCHAR(100) DEFAULT NULL,
  `submitted_at` DATETIME DEFAULT NULL,
  `purchasing_verified_by` VARCHAR(100) DEFAULT NULL,
  `purchasing_verified_at` DATETIME DEFAULT NULL,
  `accounting_verified_by` VARCHAR(100) DEFAULT NULL,
  `accounting_verified_at` DATETIME DEFAULT NULL,
  `posted_by` VARCHAR(100) DEFAULT NULL,
  `posted_at` DATETIME DEFAULT NULL,
  `reversed_by` VARCHAR(100) DEFAULT NULL,
  `reversed_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id_retur_pembelian`),
  UNIQUE KEY `uk_no_retur_pembelian` (`no_retur_pembelian`),
  KEY `idx_lpb` (`id_lpb`),
  KEY `idx_status` (`status`),
  KEY `idx_jurnal` (`id_jurnal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tb_retur_pembelian_detail` (
  `id_detail_retur_pembelian` INT(11) NOT NULL AUTO_INCREMENT,
  `id_retur_pembelian` INT(11) NOT NULL,
  `id_detail_lpb` INT(11) NOT NULL,
  `kd_barang` VARCHAR(100) NOT NULL,
  `no_lot` VARCHAR(50) DEFAULT NULL,
  `expired_date` DATE DEFAULT NULL,
  `qty_retur` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `harga_satuan` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `dpp` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `ppn` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `total` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  `kelompok_dagang` VARCHAR(10) DEFAULT NULL,
  `alasan_retur` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_detail_retur_pembelian`),
  KEY `idx_retur` (`id_retur_pembelian`),
  KEY `idx_detail_lpb` (`id_detail_lpb`),
  KEY `idx_barang_batch` (`kd_barang`, `no_lot`, `expired_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tb_retur_pembelian_log` (
  `id_log` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_retur_pembelian` INT(11) DEFAULT NULL,
  `no_retur_pembelian` VARCHAR(50) DEFAULT NULL,
  `action_type` VARCHAR(40) NOT NULL,
  `status_before` VARCHAR(30) DEFAULT NULL,
  `status_after` VARCHAR(30) DEFAULT NULL,
  `data_before` LONGTEXT DEFAULT NULL,
  `data_after` LONGTEXT DEFAULT NULL,
  `keterangan` TEXT DEFAULT NULL,
  `dilakukan_oleh` VARCHAR(100) DEFAULT NULL,
  `dilakukan_pada` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  KEY `idx_retur_log` (`id_retur_pembelian`),
  KEY `idx_action` (`action_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
