-- Migration: Buat master kelompok dagang keuangan
-- Tanggal: 2026-07-17
-- Target: tbkeu_kelompok_dagang
-- Sumber struktur: screenshot tabel kelompok dagang dari user.

CREATE TABLE IF NOT EXISTS `tbkeu_kelompok_dagang` (
  `NOINDEX` int(11) NOT NULL,
  `DESKRIPSI` varchar(150) DEFAULT NULL,
  `KODESALES` varchar(20) DEFAULT NULL,
  `KODEINVENTORI` varchar(20) DEFAULT NULL,
  `KODEHARGAPOKOK` varchar(20) DEFAULT NULL,
  `KODEKONSINYASI` varchar(20) DEFAULT NULL,
  `DEPT` varchar(20) DEFAULT NULL,
  `KODERETUR` varchar(20) DEFAULT NULL,
  `GUDANG` varchar(50) DEFAULT NULL,
  `INVENTORI` char(1) DEFAULT NULL,
  `BELI` char(1) DEFAULT NULL,
  `JUAL` char(1) DEFAULT NULL,
  `SISTEM` tinyint(1) NOT NULL DEFAULT 0,
  `TANGGALEDIT` datetime DEFAULT NULL,
  `IMAGE` varchar(255) DEFAULT NULL,
  `KODEPENGIRIMANBELI` varchar(20) DEFAULT NULL,
  `KODEPENGIRIMANJUAL` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`NOINDEX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `tbkeu_kelompok_dagang`
  (`NOINDEX`, `DESKRIPSI`, `KODESALES`, `KODEINVENTORI`, `KODEHARGAPOKOK`, `KODEKONSINYASI`, `DEPT`, `KODERETUR`, `GUDANG`, `INVENTORI`, `BELI`, `JUAL`, `SISTEM`, `TANGGALEDIT`, `IMAGE`, `KODEPENGIRIMANBELI`, `KODEPENGIRIMANJUAL`)
VALUES
  (1, 'Barang Dagangan BKP', '41011', '14010', '51010', '21019', '0', '41014', NULL, 'T', 'T', 'T', 0, '2024-12-29 08:55:53', NULL, '51013', '64010'),
  (0, 'N/A', NULL, NULL, NULL, NULL, '0', NULL, NULL, 'T', 'T', 'T', 1, '2024-12-29 08:55:53', NULL, NULL, NULL),
  (3, 'Barang Dagangan BKPS', '41012', '14011', '51011', '21019', '0', '41015', NULL, 'T', 'T', 'T', 0, '2024-12-29 08:55:53', NULL, '51013', '64010'),
  (4, 'Barang Dagangan', '41032', '14030', '51030', '21039', '0', '41034', NULL, 'T', 'T', 'T', 0, '2024-12-29 08:55:53', NULL, '51032', '64030'),
  (5, 'Barang Promosi', '41036', '14031', '51031', '21039', '0', '41034', NULL, 'T', 'T', 'T', 0, '2024-12-29 08:55:53', NULL, '51032', '64030')
ON DUPLICATE KEY UPDATE
  `DESKRIPSI` = VALUES(`DESKRIPSI`),
  `KODESALES` = VALUES(`KODESALES`),
  `KODEINVENTORI` = VALUES(`KODEINVENTORI`),
  `KODEHARGAPOKOK` = VALUES(`KODEHARGAPOKOK`),
  `KODEKONSINYASI` = VALUES(`KODEKONSINYASI`),
  `DEPT` = VALUES(`DEPT`),
  `KODERETUR` = VALUES(`KODERETUR`),
  `GUDANG` = VALUES(`GUDANG`),
  `INVENTORI` = VALUES(`INVENTORI`),
  `BELI` = VALUES(`BELI`),
  `JUAL` = VALUES(`JUAL`),
  `SISTEM` = VALUES(`SISTEM`),
  `TANGGALEDIT` = VALUES(`TANGGALEDIT`),
  `IMAGE` = VALUES(`IMAGE`),
  `KODEPENGIRIMANBELI` = VALUES(`KODEPENGIRIMANBELI`),
  `KODEPENGIRIMANJUAL` = VALUES(`KODEPENGIRIMANJUAL`);

-- Verification
SHOW CREATE TABLE `tbkeu_kelompok_dagang`;
SELECT * FROM `tbkeu_kelompok_dagang` ORDER BY `NOINDEX`;

-- Rollback manual jika diperlukan:
-- DROP TABLE `tbkeu_kelompok_dagang`;
